### PR TITLE
202 create migration task for orders 422 add basic tests, closes #442

### LINKED ISSUE #442: Create basic tests for Composite Orders migration task

### PR DESCRIPTION
**Pull request by branchedelac**
I added just a few tests for the order mapper, including one failing (skipped) for POLs because I wasn't sure at a glance how these would be created.

### CODE REVIEW

**Comment by branchedelac** [comment]
Hi @bltravis ! @fontanka16 pointed out that the commit history is messy because I had done a merge of main into my branch (in an attempt to get tests to pass). Apologies!

The only actual changes I made in my branch was creating this file, https://github.com/FOLIO-FSE/folio_migration_tools/pull/443/files#diff-b85ad920b5483a4424378af1389f02a1ff00ea353d3aa72ee91733ebdf34a7b9, so to remove the confusing history you could -- if you want to -- just copy that file into your branch and then refuse this pull request.

**Comment by branchedelac** [comment]
@fontanka16 I looked closer at my local history and realized I had done the merge from main on my local copy of Brook's branch (which I will never push), before creating my own branch from that. So that would be why the merge is not visible in this branch.

**Comment by bltravis** [comment]
@fontanka16 Not sure how to proceed with this.

**Comment by fontanka16** [comment]
@branchedelac @bltravis  since it seems to be able to merge this in fine, should we just merge this PR in?

**Comment by bltravis** [comment]
Just realized it was a branch-to-branch merge, not into main. Sure. 🤦‍♂️

**Pull request merged**
