### PR TITLE
446 add mapping depth tests for organization contacts

### PR DESCRIPTION
**Pull request by fontanka16**

### CODE REVIEW

**Comment by fontanka16** [comment]
@branchedelac, I added two more tests.

**Comment by fontanka16** [comment]
Now I feel more confident that it works.

**Comment by branchedelac** [comment]
Fantastic! I can see that the test run successfully now -- so my only comment would be that you could remove the "# TODO Make this run successfully." comments I added above my tests.

Eager for this to be merged so I can rebase it into my contacts branch!

**Review by branchedelac — APPROVED** [review]

**Comment by fontanka16** [comment]
Done

**Pull request merged**
