### PR TITLE
add tests, fix bug

### PR DESCRIPTION
**Pull request by fontanka16**

### CODE REVIEW

**Comment by fontanka16** [comment]
The only question I have is what should happen when the parsing fails

**Comment by branchedelac** [comment]
We should report that it failed (record id, field, and problem string), and return an empty string. 


Any date we "make up" is likely to be an incorrect guess, but could later be mistaken for an actual date coming from the source data. 

Leaving the field empty will clearly signal to the library that they need to -- now or some time post migration -- figure out the correct value and add it in.

**Review by bltravis — APPROVED** [review]
Looks good

**Comment by bltravis** [comment]
I'm going to go ahead and merge this so the fix is included in the release I'm planning to do tonight.

**Pull request merged**
